config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'accounts#index'

  resources :categories, only: [:new, :create, :destroy]

  resources :companies do
    resources :notes, only: [:new, :create, :destroy]

    resources :accounts do
      resources :notes, only: [:new, :create, :destroy]

      resources :credit_cards do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :debit_cards do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :bills do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :loans do
        resources :transactions, only: [:new, :create]
      end
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :bills
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
  has_many :notes, as: :notable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :company
  belongs_to :user
  belongs_to :account
  belongs_to :category

  has_one :frequency
  has_many :notes, as: :notable
  has_many :transactions
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bills
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :bills
  has_many :notes, as: :notable
  has_many :accounts
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :company
  has_many :notes, as: :notable
  has_many :transactions
  has_one :frequency

  validates :name_on_card, presence: true
  validates :card_number, presence: true, credit_card_number: true
  validates :expiration_date_month, presence: true
  validates :expiration_date_year, presence: true
  validates :amount, presence: true
end

app/models/debit_card.rb
class DebitCard < ApplicationRecord
  has_one :note
  belongs_to :user
  belongs_to :account
  belongs_to :company
  has_many :transactions
  has_one :frequency
  has_many :notes, as: :notable

  validates :name_on_card, presence: true
  validates :card_number, presence: true, credit_card_number: true
  validates :expiration_date_month, presence: true
  validates :expiration_date_year, presence: true
  validates :balance, presence: true
end

app/models/frequency.rb
class Frequency < ApplicationRecord
  belongs_to :bill
end

app/models/loan.rb
class Loan < ApplicationRecord
  has_many :notes
  has_many :bills
  has_many :transactions
  has_many :notes, as: :notable

  belongs_to :user
  belongs_to :company
  belongs_to :account
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :bill
  belongs_to :company
  belongs_to :loan
  has_many :notes, as: :notable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
  has_many :bills
  has_many :accounts
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def index
    @companies = current_user.companies
  end

  def show
    @company = CompanyDecorator.find(params[:id])
    @accounts = @company.accounts
    @notes = @company.notes
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "Success!"
      redirect_to companies_path
    else
      flash[:alert] = "Opps..Try Again"
      render :new
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :user_id,
      :name,
      :website
    )
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def all_records
    ActiveRecord::Base.transactions do
      def bills
        current_user.bills
      end

      def credit_cards
        current_user.credit_cards
      end

      def debit_cards
        current_user.debit_cards
      end
    end
  end

  # def balance(model_data)
  #   case model_data
  #   when model_data.class == Bills
  #     data = {
  #       labels: ["Bills"],
  #       datasets: [
  #         {
  #           label: "",
  #           backgroundColor: "rgba(220,220,220,0.2)",
  #           borderColor: "rgba(220,220,220,1)",
  #           data: [65, 59, 80, 81, 56, 55, 40]
  #         },
  #         {
  #           label: "My Second dataset",
  #           backgroundColor: "rgba(151,187,205,0.2)",
  #           borderColor: "rgba(151,187,205,1)",
  #           data: [28, 48, 40, 19, 86, 27, 90]
  #         }
  #       ]
  #     }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :success
      "ui green message"
    when :alert
      "ui red message"
    when :notice
      "ui blue message"
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
  def category_list
    list = []
    Category.all.each do |category|
      list.push(category.kind)
    end
    return list
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/debit_cards_helper.rb
module DebitCardsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def form_helper(params)
    if params[:credit_card_id]
      return [@company, @account, @notable, @note]
    elsif params[:account_id]
      return [@company, @notable, @note]
    else
      return [@notable, @note]
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/companies/index.html.erb
<h1>Your Companies</h1>

<ul>
  <% @companies.each do |company| %>
    <li><%= link_to "#{company.name}", company_path(company.id) %></li>
  <% end %>
</ul>
<% if @companies.empty? %>
  <p>You currently do not have any companies</p>
<% end %>

<%= link_to "Add Company", new_company_path, class: "ui green button" %>

app/views/companies/new.html.erb
<%= form_for @company, html: {class: "ui form"} do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :name, "Company Name" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

   <%= f.submit "Add Company", class: 'ui button'%>
<% end %>

app/views/companies/show.html.erb
<div class="ui">
  <div class="header">
    <h1><%= @company.name %></h1>
  </div>
</div>

<div class="ui sub header">
  <%= link_to "Website", URI::HTTP.build({:host => @company.website}).to_s, target: "_blank" %>
</div><br>

<%= @company.has_accounts? %>

<div class="ui styled accordion">

  <% @accounts.each do |account| %>
    <div class="title">
      <i class="dropdown icon"></i>
      <%= account.account_name %>
    </div>

    <div class="content">
      <p class="transition hidden">Account Number: <%= account.account_number %></p>
      <p class="transition hidden">Account Type: <%= account.kind %></p>
      <p class="transition hidden"><%= link_to "More", company_account_path(account.company_id, account.id) %></p>
    </div>
  <% end %>
</div>

<% if @notes.any?  %>

  <h1>Notes</h1>

  <div class="ui cards">
    <% @notes.each do |note| %>
      <div class="card">
        <div class="content">
          <div class="meta"><%= note.read_attribute_before_type_cast("created_at") %></div>
          <div class="description">
            <%= note.entry %><br>
            <%= link_to "Delete", company_note_path(@company.id, note.id), data: {confirm: 'Are you sure?'}, method: :delete, class: "ui red small button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= link_to "Add a Note", new_company_note_path(@company.id) %><br>
<%= link_to "Add Account", new_company_account_path(company_id: @company.id) %>