config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'accounts#index'

  resources :categories, only: [:new, :create, :destroy]

  resources :companies do
    resources :notes, only: [:new, :create, :destroy]

    resources :accounts do
      resources :notes, only: [:new, :create, :destroy]

      resources :credit_cards do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :debit_cards do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :bills do
        resources :notes, only: [:new, :create, :destroy]
        resources :transactions, only: [:new, :create]
      end

      resources :loans do
        resources :transactions, only: [:new, :create]
      end
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :bills
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
  has_many :notes, as: :notable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :company
  belongs_to :user
  belongs_to :account
  belongs_to :category

  has_one :frequency
  has_many :notes, as: :notable
  has_many :transactions
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bills
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :bills
  has_many :notes, as: :notable
  has_many :accounts
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :company
  has_many :notes, as: :notable
  has_many :transactions
  has_one :frequency

  validates :name_on_card, presence: true
  validates :card_number, presence: true, credit_card_number: true
  validates :expiration_date_month, presence: true
  validates :expiration_date_year, presence: true
  validates :amount, presence: true
end

app/models/debit_card.rb
class DebitCard < ApplicationRecord
  has_one :note
  belongs_to :user
  belongs_to :account
  belongs_to :company
  has_many :transactions
  has_one :frequency
  has_many :notes, as: :notable

  validates :name_on_card, presence: true
  validates :card_number, presence: true, credit_card_number: true
  validates :expiration_date_month, presence: true
  validates :expiration_date_year, presence: true
  validates :balance, presence: true
end

app/models/frequency.rb
class Frequency < ApplicationRecord
  belongs_to :bill
end

app/models/loan.rb
class Loan < ApplicationRecord
  has_many :notes
  has_many :bills
  has_many :transactions
  has_many :notes, as: :notable

  belongs_to :user
  belongs_to :company
  belongs_to :account
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :bill
  belongs_to :company
  belongs_to :loan
  has_many :notes, as: :notable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
  has_many :bills
  has_many :accounts
  has_many :credit_cards
  has_many :transactions
  has_many :debit_cards
  has_many :loans
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def index
    @accounts = current_user.accounts
    @credit_cards = current_user.credit_cards
    @debit_cards = current_user.debit_cards
    @bills = current_user.bills
  end

  def show
    @account = Account.find(params[:id])
    @company = Company.find(@account.company_id)
    @credit_cards = @account.credit_cards
    @debit_cards = @account.debit_cards
    @notes = @account.notes
    @loans = @account.loans
  end

  def new
    @account = Account.new
    @company = Company.find(params[:company_id])
  end

  def create
    @company = Company.find(params[:company_id])
    @account = @company.accounts.new(account_params)
    if @account.save
      flash[:success] = "Success!"
      redirect_to companies_path
    else
      flash[:alert] = "Opps..Try Again"
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(
      :company_id,
      :user_id,
      :account_name,
      :account_number,
      :kind
    )
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def all_records
    ActiveRecord::Base.transactions do
      def bills
        current_user.bills
      end

      def credit_cards
        current_user.credit_cards
      end

      def debit_cards
        current_user.debit_cards
      end
    end
  end

  # def balance(model_data)
  #   case model_data
  #   when model_data.class == Bills
  #     data = {
  #       labels: ["Bills"],
  #       datasets: [
  #         {
  #           label: "",
  #           backgroundColor: "rgba(220,220,220,0.2)",
  #           borderColor: "rgba(220,220,220,1)",
  #           data: [65, 59, 80, 81, 56, 55, 40]
  #         },
  #         {
  #           label: "My Second dataset",
  #           backgroundColor: "rgba(151,187,205,0.2)",
  #           borderColor: "rgba(151,187,205,1)",
  #           data: [28, 48, 40, 19, 86, 27, 90]
  #         }
  #       ]
  #     }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :success
      "ui green message"
    when :alert
      "ui red message"
    when :notice
      "ui blue message"
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
  def category_list
    list = []
    Category.all.each do |category|
      list.push(category.kind)
    end
    return list
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/debit_cards_helper.rb
module DebitCardsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def form_helper(params)
    if params[:credit_card_id]
      return [@company, @account, @notable, @note]
    elsif params[:account_id]
      return [@company, @notable, @note]
    else
      return [@notable, @note]
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/index.html.erb
<%= link_to 'New Category', new_category_path %>

<h1>Accounts</h1>

<table class="ui celled table">
 <thead>
   <th>Account Name</th>
   <th>Company Name</th>
   <th>Type</th>
   <th>Options</th>
 </thead>

 <tbody>

   <% @accounts.each do |account| %>
     <tr>
       <td><%= link_to "#{account.account_name}", company_account_path(account.id, account.company_id) %></td>
       <td><%= Company.find(account.company_id).name %></td>
       <td><%= account.kind %></td>
       <td>
         <%= link_to "Delete", company_account_path(account.company_id, account.id), method: :delete, class: "ui red small button" %>
         <%= link_to "Edit", edit_company_account_path(account.company_id, account.id), class: "ui yellow small button" %>
      </td>
     </tr>
   <% end %>
 </tbody>
</table>


<h1>Credit Cards</h1>

<table class="ui celled table">
 <thead>
   <th>Name on card</th>
   <th>Company Name</th>
   <th>Card Number</th>
   <th>Options</th>
 </thead>

 <tbody>

   <% @credit_cards.each do |card| %>
     <tr>
       <td><%= card.name_on_card %></td>
       <td><%= link_to Company.find(card.company_id).name, company_account_path(card.id, card.company_id) %></td>
       <td><%= card.card_number %></td>
       <td>
         <a href="#" class="ui small button">Pay</a>
         <%= link_to "Delete", company_account_credit_card_path(card.company_id, card.account_id ,card.id), method: :delete, class: "ui red small button" %>
       </td>
     </tr>
   <% end %>
 </tbody>
</table>

<h1>Debit Cards</h1>

<table class="ui celled table">
 <thead>
   <th>Name on card</th>
   <th>Company Name</th>
   <th>Card Number</th>
   <th>Options</th>
 </thead>

 <tbody>

   <% @debit_cards.each do |card| %>
     <tr>
       <td><%= card.name_on_card %></td>
       <td><%= link_to Company.find(card.company_id).name, company_account_path(card.id, card.company_id) %></td>
       <td><%= card.card_number %></td>
       <td>
         <%= link_to "Delete", company_account_debit_card_path(card.company_id, card.account_id ,card.id), method: :delete, class: "ui red small button" %>
       </td>
     </tr>
   <% end %>
 </tbody>
</table>

<h1>Bills</h1>

<table class="ui celled table">
 <thead>
   <th>Company</th>
   <th>Account</th>
   <th>Date</th>
   <th>Amount</th>
   <th>Options</th>
 </thead>

 <tbody>

   <% @bills.each do |bill| %>
     <tr>
       <td><%= Company.find(bill.company_id).name %></td>
       <td><%= Account.find(bill.account_id).account_name %></td>
       <td><%= bill.next_due_date %></td>
       <td><%= bill.amount %></td>
       <td>
         <a href="#" class="ui small button">Pay</a>
         <%= link_to "Delete", company_account_bill_path(bill.company_id, bill.account_id, bill.id), method: :delete, class: "ui red small button" %>
       </td>
     </tr>
   <% end %>
 </tbody>
</table>

app/views/accounts/new.html.erb
<%= form_for [@company, @account], html: { class: "ui form" } do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="five wide field">
    <%= f.label :account_name %>
    <%= f.text_field :account_name %>
  </div>

  <div class="five wide field">
    <%= f.label :account_number %>
    <%= f.text_field :account_number %>
  </div>

  <div class="five wide field">
    <%= f.label :kind, "Type" %>
    <%= f.text_field :kind %>
  </div>

  <%= f.submit "Add Account", class: 'ui button'%>
<% end %>

app/views/accounts/show.html.erb
<h3>Account Name: <%= @account.account_name %></h3>
<h3>Type: <%= @account.kind %></h3>
<h3>Account Number: <%= @account.account_number %></h3>

<% if @credit_cards.any? %>
  <h1>Credit Cards</h1>

  <table class="ui celled table">
    <thead>
      <th>Account Name</th>
      <th>Company Name</th>
      <th>Options</th>
    </thead>

    <tbody>
      <% @credit_cards.each do |card| %>
        <tr>
          <td><%= card.name_on_card %></td>
          <td><%= Company.find(card.company_id).name %></td>
          <td><a href="#" class="ui small button">Pay</a>
            <%= link_to "Remove", company_account_path(@account.company_id, @account.id), data: {confirm: 'Are you sure?'}, method: :destroy, class: "ui red small button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end  %>

<% if @debit_cards.any? %>
  <h1>Debit Cards</h1>

  <table class="ui celled table">
    <thead>
      <th>Account Name</th>
      <th>Company Name</th>
      <th>Options</th>
    </thead>

    <tbody>
      <% @debit_cards.each do |card| %>
        <tr>
          <td><%= card.name_on_card %></td>
          <td><%= Company.find(card.company_id).name %></td>
          <td><a href="#" class="ui small button">Pay</a>
            <%= link_to "Remove", company_account_path(@account.company_id, @account.id), data: {confirm: 'Are you sure?'}, method: :destroy, class: "ui red small button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end  %>

<% if @loans.any? %>
  <h1>Loans</h1>
  <table class="ui celled table">
    <thead>
      <th>Interest</th>
      <th>Total</th>
      <th>Options</th>
    </thead>

    <tbody>

      <% @loans.each do |loan| %>
        <tr>
          <td><%= loan.interest %></td>
          <td><%= loan.amount %></td>
          <td>
            <a href="#" class="ui small button">Pay</a>
            <%= binding.pry %>
            <%= link_to "Remove", company_account_loan_path(loan.company_id, loan.account_id, loan.id), data: {confirm: 'Are you sure?'}, method: :delete, class: "ui red small button" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end  %>

<% if @notes.any?  %>
  <h1>Notes</h1>

  <div class="ui cards">
    <% @notes.each do |note| %>
      <div class="card">
        <div class="content">
          <div class="meta"><%= note.read_attribute_before_type_cast("created_at") %></div>
          <div class="description">
            <%= note.entry %><br>
            <%= link_to "Delete", company_account_note_path(@company.id, @account.id, note.id), data: {confirm: 'Are you sure?'}, method: :delete, class: "ui red small button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<p>Options</p>
<%= link_to "New Credit Card", new_company_account_credit_card_path(@account.company_id, @account.id) %><br>
<%= link_to "New Debit Card", new_company_account_debit_card_path(@account.company_id, @account.id) %><br>
<%= link_to 'New Bill', new_company_account_bill_path(@account.company_id, @account.id) %><br>
<%= link_to "Add a new Note", new_company_account_note_path(@account.company_id, @account.id) %><br>
<%= link_to "Add new account", new_company_account_path(company_id: @company.id) %><br>
<%= link_to "Add a new Loan", new_company_account_loan_path(@account.company_id, @account.id) %><br>